### ISSUE TITLE
Use TToken instead of MyERC20

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge-sol#6]

**Comment by ailisp** [comment]
Is this really needed? MyERC20 is just https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol (with additional export `_mint` to `mint`), is considered very solid

**Comment by Kouprin** [comment]
> Is this really needed? MyERC20 is just https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol (with additional export `_mint` to `mint`), is considered very solid

Low priority. In general we should:
1. less duplicate code;
2. more use developed by us staff.
The 2 is important because of taking things under our control. As TToken is implemented, having another source is dup.

**Comment by abacabadabacaba** [comment]
Closing because TokenLocker was removed.
